### PR TITLE
Introduction to OOP

### PR DESCRIPTION
**Pull request by RMeli**
Simple introduction to OOP. This is written with #46 in mind, but can be moved in the advanced topics as well.

Starts addressing #23 and #24.

### CODE REVIEW

**Comment by arm61** [comment]
I am crazy busy this whole week, then off on Monday. So if @j-m-dean or @alexsquires have a chance to look at this feel free. If not I can deal with it next week (sorry for the delay @RMeli).

**Review by j-m-dean — COMMENTED** [review]
I like it. I think it introduces a complex topic, using the foundations already introduced, whilst applying potentially real world examples. 

Sorry about there being so many comments. Action or ignore the suggestions below, as you see fit. 

**Comments/Suggestions:**

-Pre-requisites section before notebook begins. It is in the first sentence, but would be useful for stylist consistency. 

- I think in the style guide we set on first person, so “I/we”, instead of second person, “you”. The justification being it is a friendlier tone and makes the student feel guided through the notebooks. 

- I don’t think we have defined “pass” by this point, so a comment just describing why it is there may be useful

- We have not introduced masks by this point. They may require a brief introduction before use 

- Currently there are no figures. It would be nice to have some figures to break the text up a bit. Maybe an image of acetylene, and a way of visualising a mask and/or a class? 

**Typos:**

- In the programming jargon —> In programming jargon 

- Therefore should be usually processed together —> therefore should be processed together

- To represent H2 —> a hydrogen gas molecule, just because H2 was used to represent the second hydrogen previously

- Can you think a way of tie together —> Can you think of a way of tying together 

- Object allows you to tie together —> Objects allow you to tie together

- an object (usually called instance in this context) as an house built following said plan —> an object (usually called an instance in this context) as a house built following said plan

- the __init__ method takes a self as one —> the __init__ method takes self as one

- the object itself (which is an instance of the class SimpleMolecule) as first argument of a method —> the object itself (which is an instance of the class SimpleMolecule) as the first argument of a method

- The variables stored withing a class —> The variables stored within a class

- inisialised using the __init__ method. —> initialised 

- This example also clarifies a bit more the meaning of self —> This example helps clarify the meaning of self

- but being an instance of the Molecule, there —> but being an instance of the Molecule class, there

- In this section we introduced a lot basic principles —> In this section we have introduced a lot of basic principles

- The class keyword allows to define a class in Python —> The class keyword allows us to define a class in Python

**Comment by RMeli** [comment]
Thank you for the extensive review @j-m-dean ! Sorry for the many typos, I thought I removed most of them but obviously the spell checker is not working well with Jupyter.

Regarding masks, should we introduce them here or add something to the `numpy` section?

---

TODOs:

* [x] Add pre-requisites section
* [x] Change to "I/we"
* [x] Comment on `pass` keyword
* [ ] Introduce masks with `numpy` (see above)
* [ ] Add figures
  * [x] Acetylene
  * [x] Class ([UML](http://uml.org/))
  * [ ] Masking
* [x] Fix typos

Additional TODOs:

* [x] Add Google-style doctsrings; they are introduced in the section about functions.

**Comment by RMeli** [comment]
@j-m-dean there is only one typo I did not address (see comment below). Please let me know if you do not agree with my explanation and I'll be happy to make the suggested change.

---

> Therefore should be usually processed together —> therefore should be processed together

I used "usually" because some operations can be performed on only part of the data (i.e. rotating a molecule will involve coordinates only).

**Comment by j-m-dean** [comment]
Ah, I see why you have added the usually now. However, I do not think "therefore should be usually processed together" makes sense. May I suggest: "therefore should be, in most cases, processed together"?

**Comment by RMeli** [comment]
Sorry for the delay on this, I've been very busy lately. I added UML-style images for the classes. This should address all the comments beside masking. However, I think that the concept of masking is better in the section about `numpy` arrays. What do you think?

**Comment by arm61** [comment]
Need to merge https://github.com/pythoninchemistry/intro_python_chemists/commit/7a0ed35e679e0f1ba73ed7576013378fd1fd97f9 into your code to get it to pass CI btw, see issue #71 

I will leave the actual review to @j-m-dean

**Comment by j-m-dean** [comment]
Looks great! Thank you for all the added stuff. I agree, it does not make sense to introduce masks in this section. I'll add in a little section at the bottom of numpy_arrays at some point.

**Comment by RMeli** [comment]
Sounds good. Thank you for all the valuable feedback @j-m-dean !

**Pull request merged**
