### PR TITLE
Collections

### PR DESCRIPTION
**Pull request by arm61**
First draft of collections. 

@j-m-dean I welcome suggestions of how to improve the text, things I have missed out, and ideas for an exercise. 

Pinging #8

### CODE REVIEW

**Comment by j-m-dean** [comment]
I think it covers all the basics, some comments I jotted down as I read were:
- [x]  bullet points at start: Dictionarys -> Dictionaries
- [x] Can concatenate tuples together
- [x] “This notation can be a bit confusing, as this notation is inclusive then exclusive” - a diagram would be useful here. 
- [x] Tuple items do not have to be a consistent type
- [x] X-ray scatter length is a very niche piece of information
- [x] Could bulk out the dictionary section comparing it to a traditional dictionary. The key being the word and the value being its meaning. This is how I was introduced and it has stuck with me since.
- [x] “Finally, the items in a dictionary need not be single varibles,” - variables
- [x] personally I would introduce lists before tuples as students are more likely to use lists than tuples. 

There are no diagrams in the tutorial at all. Very information dense. No “breathing” space for students to think about concepts. I think list indexing can be learnt easily by visualisation.

**Comment by j-m-dean** [comment]
Potential exercises:
- Create a dictionary of the first row of the d block elements where the keys are the elements names and the values are the valence electrons. 
- Using list slicing extract the even, odd, values less than 5, values greater than five, values between 3 and 7 for the list [1,2,3,4,5,6,7,8,9,10]. (Boring but practical- I cannot think of any examples where you would need every other/third data points)

**Comment by arm61** [comment]
@j-m-dean that's me dealt with the comments (I think) and added the transition metal exercise that you suggested. So any other comments welcome!

**Comment by j-m-dean** [comment]
@arm61  Looks great! 👏 🎉 

Couple of typos and then it is good to go:
-"So it is possble for a list to be made up of disperate forms of information." - disparate (above code cell 16) 
- "The immutability of a tupe does not mean that the whole variable cannot be overwritten." - tuple (above code cell 24)

**Comment by arm61** [comment]
Done and going to pull

**Pull request merged**
