### PR TITLE
add first draft of stats

### PR DESCRIPTION
**Pull request by arm61**
This is a *first* draft of the stats section. I want to add more, but I am not sure exactly what yet. 

This should act as a jumping off ground.

### CODE REVIEW

**Comment by arm61** [comment]
If @RMeli or @WG150 have comments they are more than welcome.

**Comment by j-m-dean** [comment]
Looks alright, but... "This plot gives the probability that a particular value of $k$ would be measured" is not correct. The probability is deduced from an integral of the probability density function evaluated between two values. Having a pdf with values (> 1) may confuse students who see the pdf as probability. You could use "k_300 = np.array([13.31, 13.13, 13.17, 13.23, 12.17])" instead so all pdf values are below one. But that is still lying to the students if we say the pdf is equivalent to probability.

**Comment by arm61** [comment]
this is a good point, getting density and distribution mixed up. Will sort.

**Comment by arm61** [comment]
A lazy fix, I have changed it to relative likelihood, which I think is more accurate

**Pull request merged**
