### PR TITLE
optimization tutorial

### PR DESCRIPTION
**Pull request by j-m-dean**
Written an introduction to the script.optimize.minimize function. It is definitely rough around the edges but a skeleton is there. 

Comments and improvements welcomed!

### CODE REVIEW

**Comment by arm61** [comment]
The build is failing cause the file is called `optimization.ipynb` instead of `optimisation.ipynb` (which opens a whole can of worms about if we should use British or American English)

**Comment by j-m-dean** [comment]
A can of worms whose decision on can be deferred until later down the line. I've changed the file name.

**Comment by j-m-dean** [comment]
and_or statement also completed.

**Review by arm61 — CHANGES_REQUESTED** [review]
Some comments:
- `git rm` the `__pycache__` and recommit to get rid of these files
- move the `periodic_table_20.py` into the basics folder then you won't need the `import sys` and the path insert
- Is there are a way to make a more chemistry example in the minimisation stuff or do you think that comes with the fitting exercise?
- There is some weird formatting (the degree symbol in the and_or for example. But we can sort that at a later stage (as it might just be Github's rendering of the notebook)

**Comment by j-m-dean** [comment]
There is probably loads of chemistry examples. The only one I think students would have encountered before, that is easy to visualise with the rolling ball analogy, is radial wave functions. They (can) have numerous minima at different magnitudes. But those functions can often appear scary when written down. 

I could add a few of them at the bottom of the introductory minimisation notebook, but I think the simple functions are the gentlest introduction. If the radial wave functions are introduced it also allows an illustration that the minimize function will not always stop in a minimum. If the initial guess is too larger minimize will stop in the "tail" of the radial wave function. 

Thoughts?

**Comment by bjmorgan** [comment]
Finding the spatial minima of wavefunctions is not something students are ever asked to do though.

**Comment by arm61** [comment]
Doesn't mean that it isn't an interesting things to do though...?

**Comment by j-m-dean** [comment]
Bare bones of both the optimisation and and_or notebooks should be there now. Radial wave functions were put into the optimisation tutorial. The confusing tunnel analogy was removed and a chemical example of molecular logic gates was added.

**Review by arm61 — APPROVED** [review]

**Pull request merged**
