### PR TITLE
documentation

### PR DESCRIPTION
**Pull request by alexsquires**
I've added a documentation section with a focus on writing as opposed to reading. I thought this would be a doss, but turns out it's hard. Happy to be beaten over the head with the opinions of others.

### CODE REVIEW

**Comment by arm61** [comment]
Thoughts:
- [x] Change title to "Writing documentation", then #64 will precede this section as it is explaining how to find and read documentation. 
- [x] Add "reading and finding documentation" to prerequisites
- [x] Maybe don't contextualise the first paragraph in "research", perhaps "learning and research" (keep the audience open as possible)
- [x] 'functional' to *functional* (formating IDGAF really)
- [x] Make 'the code below solves Bragg's law for an orthorombic crystal to determine the Bragg angle associated with a given miller plane' bold
- [x] make the # symbol code case
- [x] `# define miller indicies` to `# define miller indices`
- [ ] Are you wanting comments and docstrings to be two separate sections?
- [x] "emphasis" to "emphasise"
- [x] "arguemnts" to "arguments"

I like this

**Comment by alexsquires** [comment]
> * [ ]  Are you wanting comments and docstrings to be two separate sections?

My thinking here was that docstrings require an appreciation of functions, but I don't feel like an understanding of basic documentation should necessitate understanding functions, so I separated them out. I'm not strongly attached to this way of working though.

**Comment by arm61** [comment]
I personally would be happy with them together, just change the name of that subsection to "Docstrings" or something and add functions to the overall prerequisites (this part will definitely be coming after the functions part in the structure of the book so it should be fine).

**Review by arm61 — APPROVED** [review]

**Comment by arm61** [comment]
Happy for you to merge this @alexsquires

**Pull request merged**
