### PR TITLE
loops tutorial

### LINKED ISSUE #7: Add exercises to functions
Currently there are no `#### Exercise` in the functions section. It would be nice to include some.

### LINKED ISSUE #12: Loops
Write a section introducing:

- for loops
- while loops

This should include some discussion of the `range()` iterator, the difference between the loops and `break`/`continue`.

### PR DESCRIPTION
**Pull request by j-m-dean**
This tutorial definitely needs some visuals but I can't think of how to visualise loops. Recommendations would be appreciated.

### CODE REVIEW

**Comment by j-m-dean** [comment]
I've added some flowcharts which, I think, are fairly good visualisation tools.

**Comment by j-m-dean** [comment]
Added momentum and alternative kinetic energy calculation as exercise to functions.

**Review by arm61 — COMMENTED** [review]
Some comments:
- would it be less confusing to have the `periodic_table_20` dict of dicts defined in the .py file not as a function call, then just use `from periodic_table_20 import `pt_20` or something like that. I just worry that the `pt.create()` might be able bit much
- the indented lists bit can do with some ironing but I think that will come with time 
- plotting is used, but not included in the *prerequisites*, I suggest mentioning that plotting is covered in < link to the simple plotting bit >.

**Comment by j-m-dean** [comment]
- Yup I'll change that
- Yeah, it is a bit fuddled. I'll keep a mental note to revisit in a couple of weeks time.
- There is plotting, but as plotting is not covered by this point all the plotting is done for them and hidden in a plot_wavefunction() function which is imported. I thought this was best as they had come across functions but not plotting. I'll mention that plotting is included later on as a note.

**Pull request merged**
