### PR TITLE
add advanced plotting

### PR DESCRIPTION
**Pull request by alexsquires**
Don't hold back, went round the houses a few times with this one
.

### CODE REVIEW

**Comment by arm61** [comment]
Will read on Monday. But it is LaTeX not LateX 😉

**Comment by alexsquires** [comment]
What a fool I've been.

**Comment by arm61** [comment]
Comments:
- LaTeX not LateX
- uses not usues in first sentence of "Application to chemistry..." section
- "hae" to "have" in second sentence of same section
- perhaps "carbon in iron" should be "carbon and iron" but maybe not cause I am not sure if you alloy something in something else or alloy them together (hence and). This is in that same first paragraph
- some stylising things, like trying to keep the line lengths shorter and spacing after commas in code (this isn't a big deal cause formatting is not the focus just now)
- I don't find an explanation for what `1,1` means in the subplots arguments
- after the note on latex there is this `$500~\mathrm{K}$`, not sure why the tilde is there (it might just be the GitHub latex formatting being weird.
- Second sentence in the last paragraph before the plot with three needs a capital letter at the start.
- Nested list comprehension? offt. Can this list of lists be made simpler?
- Final paragraph third sentence "ar" to "are"
- In this final paragraph, can you include a link to the ppl docs that show all of the rcParams options? https://matplotlib.org/tutorials/introductory/customizing.html

**Comment by j-m-dean** [comment]
I like it, very thorough!

Suggestions/Comments: 

-May be useful to state that nearest-neighbour interactions are the only relevant interactions in the model alloy 

-“for each of the bond” —> “For each of the” in the paragraph above the three subplots

-“let’s add a bit” —> “Let’s add a bit” in the paragraph below the three subplots

-Some inconsistencies with lets and let’s

-In the 3x3 subplots where there are only two plotted the third row has a different y axis

-For the 3x3 subplots where all curves are plotted, does Energy / kJ need to be on all y axes?

-“free energy of mixing becones negative” —> “becomes”, paragraph above exercise

-sqrt(x) may look nicer as r’$\sqrt{x}$’ in appendix

**Comment by alexsquires** [comment]
> * ~~LaTeX not LateX~~
> * ~~uses not usues in first sentence of "Application to chemistry..." section~~
> * ~~"hae" to "have" in second sentence of same section~~
> * ~~perhaps "carbon in iron" should be "carbon and iron" but maybe not cause I am not sure if you alloy something in something else or alloy them together (hence and). This is in that same first paragraph~~ (Not to sure on this one, seem to remember my 4th year lecturer referring to the minor component being alloyed _in_ the main component, but and is unambiguous)
> * ~~some stylising things, like trying to keep the line lengths shorter and spacing after commas in code (this isn't a big deal cause formatting is not the focus just now)~~ I changed some of the worst offenders
> * ~~I don't find an explanation for what `1,1` means in the subplots arguments~~
> * ~~after the note on latex there is this `$500~\mathrm{K}$`, not sure why the tilde is there (it might just be the GitHub latex formatting being weird.~~ the '~' ensures the correct spacing between 500 and K. 
> * ~~Second sentence in the last paragraph before the plot with three needs a capital letter at the start.~~
> * ~~Nested list comprehension? offt. Can this list of lists be made simpler?~~ Had a go, not sure if it's much better, open to suggestions
> * ~~Final paragraph third sentence "ar" to "are"~~
> * ~~In this final paragraph, can you include a link to the ppl docs that show all of the rcParams options? https://matplotlib.org/tutorials/introductory/customizing.html~~ this was the link I used, have clarified that that information in in there


> I like it, very thorough!
> 
> Suggestions/Comments:
> 
> ~~-May be useful to state that nearest-neighbour interactions are the only relevant interactions in the model alloy~~
> 
> ~~-“for each of the bond” —> “For each of the” in the paragraph above the three subplots~~
> 
> ~~-“let’s add a bit” —> “Let’s add a bit” in the paragraph below the three subplots~~
> 
> ~~-Some inconsistencies with lets and let’s~~
> 
> ~~-In the 3x3 subplots where there are only two plotted the third row has a different y axis~~ I think that's because there's no data plotted in the third row, should I change this?
> 
> ~~-For the 3x3 subplots where all curves are plotted, does Energy / kJ need to be on all y axes?~~ probably not, gone.
> 
> ~~-“free energy of mixing becones negative” —> “becomes”, paragraph above exercise~~
> 
> ~~-sqrt(x) may look nicer as r’$\sqrt{x}$’ in appendix~~

**Pull request merged**
