### PR TITLE
add simple plotting

### PR DESCRIPTION
**Pull request by alexsquires**
Simple plotting chapter for your consideration.

### CODE REVIEW

**Comment by arm61** [comment]
Just realised that the contributing guidelines still say to build the book...I have automated that process so could you remove the `_build` directory?

**Comment by arm61** [comment]
I have assigned @j-m-dean and myself to review. Whomever gets the time first can have a bash.

**Comment by arm61** [comment]
Not pulling the rug out from you but following a chat with @bjmorgan a prerequisites bit at the start of the section will be useful down the line (https://github.com/pythoninchemistry/intro_python_chemists#current-aim). Just something to be conscious of cause I will mention it in a review (and go and add it to the content @j-m-dean and I have done already tomorrow am)

**Review by j-m-dean — COMMENTED** [review]
I really like it! It's tidy, fun, and professional. 

Typos I noticed were:
“matplot.pyplot.plot()” -  matplotlib.pyploy.plot()  first paragraph
“relationship taking the data as two arguments. the arguments are positional" - capital T
second paragraph
“despite sometimes being unecesssary for a quick visualisation” - unnecessary 
A note on plt.show()
“−Ea is the activation energy” - the negative is not required
Arrhenius terms
“same functionalility as plt.plot() taking additional” - functionality 
Error bar section
“Say we want compare the probablility distribution of three atomic orbitals” - probability & “want to”
Radial wave functions section
“ 3s, 3p, and 3d orbirals respectivley” orbitals & respectively 
Numerator in the first term of the 3s radial wave function should be 2. It is in the function but not in the text. 

Comments:
- very thorough comments in the code. I quite like it. Maybe we should increase the comments on the other notebooks? 
- (Just personal preference but) the radial wave functions plot could use a dotted horizontal line at R =0 to make nodes and asymptotes clear. 
- radial_probability_function takes in one argument but uses two (r_value and r_values) and has orbital as an input variable in the docstring but not used in the function? 

I think the tutorial flows really nicely and the exercises complement the examples well.

**Comment by arm61** [comment]
@j-m-dean is you are happy feel free to merge the PR 🎉

**Pull request merged**
