### PR TITLE
Surface plots added

### PR DESCRIPTION
**Pull request by symmy596**
A first draft of the surface plot section. 
* Scatter plots
* Contour plots
* Contourf plots
* Combination of contour and contourf
*

### CODE REVIEW

**Comment by arm61** [comment]
Any chance of a more chemistry focused example? Maybe bond angles or something?

**Comment by j-m-dean** [comment]
Surface plots lends itself to transition state theory quite nicely if you're looking for a more chemistry example.

**Comment by j-m-dean** [comment]
http://www.umich.edu/~elements/fogler&gurmen/html/03chap/html/transition/index.htm

Figure PRS.3B-3, is the mental model I think of for TST.

**Comment by arm61** [comment]
Bumping this @symmy596. In case you forgot 😉

**Comment by arm61** [comment]
I am going to merge what @symmy596 made and then finish it off with a chemistry example myself.

**Pull request merged**
