### PR TITLE
IR Spectra longer exercise

### PR DESCRIPTION
**Pull request by arm61**
Thoughts? I dropped the MCMC stuff compared to the ch40208 cause I wanted to focus on the "working with data" part.

### CODE REVIEW

**Comment by arm61** [comment]
pinging #34

**Review by j-m-dean — COMMENTED** [review]
Some comments: 
- [x] Previous notebooks had prerequisites before importation of modules
- [x] “Benyl alcohol. YOu” —> benzyl alcohol. You (aims section)
- [x] “tolene.csv” —> toluene.csv (aims section)
- [x] “Large feature in the toulene isolated data” —> toluene (above the fitting section)
- [x] “In order to determine this line of best fit, we use a process called, we have a metric that we want to minimise which represents the difference between the data and the model (the straight line).” - I think you’ve re-written this and not deleted some of the previous text (fitting section)
- [x] “straight line model through, linear regression, a mathematical ” —> “straight line model through linear regression, a mathematical”
- [x] Axis titles on plots
- [x] “to notice that the vales for wavenumber” —> values (interpolation section)
- [x] “spectra are not the sam” —>same (interpolation section)
- [x] “Additionaly, since our model”—> additionally (interp)
- [x] “be created form mixing the toulene”—>from, toluene (interpolation)
- [x] “within the exisiting range”—> existing(interp)
- [x] A clearer explanation of terms may be required for the terms y_model,i etc. Maybe give an example. This was often something students struggled understanding in CH40208.

Are model solutions provided for the longer exercises?

**Comment by arm61** [comment]
Cheers @j-m-dean, I have pushed some changes. Let me know if the additional detail that covers your final point is enough.

On the model answers question, I have opened a separate issue (#60) to discuss this.

**Comment by j-m-dean** [comment]
@arm61 the explanation is much clearer. I think students will have an easier time understanding it now. There is a typo in the final bullet point though: "so is the gradient is 1 and intercept is 0" --> so if the...

**Comment by arm61** [comment]
Fixed, I will merge once it passes.

**Pull request merged**
